# Generated by Django 4.2 on 2023-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.CharField(default='', max_length=256),
        ),
    ]
